### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vasmarfas** [BarsTiger/TeleDiffusionBot#11]
**Please add a whitelist (as example, in .env file) in which it is possible to prescribe chat IDs in which the bot will respond. Everyone else will ignore. Thanks**
upd. https://github.com/BarsTiger/TeleDiffusionBot/pull/13/commits/2dda780d3f558e46540b4d2ed2c772f9a8988065

**Comment by seel2304** [comment]
And also, if it doesn’t make it difficult, make a separate cooldown for commands for admins and for users (for example, remove cd for administrators in general so that they can use all commands, including generation and model change without restrictions)
