### ISSUE TITLE
Bot-Stopped

### ISSUE THREAD

**Issue by demasakbar** [BarsTiger/TeleDiffusionBot#15]
Operating System : Windows 11
Python : 3.10.9
Directory Installation : D:/path/to/bot/sd/TeleDiffusionBot

I have done the following (With PowerShell) : 
`python -m venv venv` after that 
`venv/Scripts/activate.ps1` after that
`pip install -r requirements.txt`

I have also created `.env` file dengan format :
```
TOKEN='xxxxxxxxxxxxxxxxxxxxxxx'
ADMIN='xxxxxxxxxxxx'
DB_CHAT='-xxxxxxxxxxxx'
DB_PATH='D:/path/to/bot/sd/TeleDiffusionBot/dbImages/'
ENCRYPTION_KEY='xxxxxx'
ARCHIVE_CHAT=
```
But After i Launch with command `python main.py`, There is an error message : `Bot-Stopped`

**Comment by demasakbar** [comment]
For that i have solved change `DB_PATH=.` (dot)

**Comment by BarsTiger** [comment]
Is your issue solved?

**Comment by demasakbar** [comment]
Problem Solved. https://github.com/BarsTiger/TeleDiffusionBot/issues/16
