### ISSUE TITLE
aiogram 

### ISSUE THREAD

**Issue by javad-fallah-official** [BarsTiger/TeleDiffusionBot#21]
Hi, aiogram module have so many problems with your project 
please say what version we have to use
-thanks

**Comment by javad-fallah-official** [comment]
its the eror i get  
File "----\TeleDiffusionBot\bot\common.py", line 3, in <module>
    from aiogram.contrib.fsm_storage.memory import MemoryStorage
ModuleNotFoundError: No module named 'aiogram.contrib'

**Comment by BarsTiger** [comment]
They upgraded to aiogram3. Use latest aiogram 2.x version

**Comment by javad-fallah-official** [comment]
can you say an exact version?
