### ISSUE TITLE
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/cryptography/fernet.py", line 113, in _get_unverified_token_data     raise TypeError("token must be bytes or str")

### ISSUE THREAD

**Issue by johndpope** [BarsTiger/TeleDiffusionBot#3]
python main.py
TELE-DIFFUSION-BOT
All handlers registered
All callbacks registered
Commands registered
Bot will start now
First database pulling for this instance - DB is up-to-date
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError('token must be bytes or str')>
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/handlers/initialize/all_messages.py", line 13, in sync_db_filter
    if not await ping():
           ^^^^^^^^^^^^
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/modules/api/ping.py", line 6, in ping
    endpoint = decrypt(db[DBTables.config].get('endpoint'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/Documents/gitWorkspace/TeleDiffusionBot/bot/db/encryption.py", line 25, in decrypt
    return fernet.decrypt(s).decode()
           ^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/cryptography/fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/cryptography/fernet.py", line 113, in _get_unverified_token_data
    raise TypeError("token must be bytes or str")
TypeError: token must be bytes or str

**Comment by johndpope** [comment]
I'm using this ENCRYPTION_KEY='testtestsetsetsetseset'

**Comment by johndpope** [comment]
I went through and hacked the 
 decrypt(db[DBTables.config].get('endpoint'))

-> to become 

config.py
END_POINT = os.getenv('END_POINT')


.env 

END_POINT='http://0.0.0.0:7860'


from .env

**Comment by johndpope** [comment]
WEV-ChatGPT, [13/3/23 10:43 PM]
😶‍🌫️ Specify arguments for this command. Check /help

WEV-ChatGPT, [13/3/23 10:44 PM]
⏳ Enqueued...

WEV-ChatGPT, [13/3/23 10:44 PM]
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'



WEV-ChatGPT, [13/3/23 10:44 PM]
⏳ Enqueued...

WEV-ChatGPT, [13/3/23 10:44 PM]
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'



❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'

**Comment by johndpope** [comment]
everything is enabled - and yet - not progressing.

John Pope, [13/3/23 10:43 PM]
/setprompt@WEVChatGPTBot hot dog

WEV-ChatGPT, [13/3/23 10:43 PM]
😶‍🌫️ Specify arguments for this command. Check /help

WEV-ChatGPT, [13/3/23 10:44 PM]
⏳ Enqueued...

WEV-ChatGPT, [13/3/23 10:44 PM]
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'

John Pope, [13/3/23 10:46 PM]
John Pope, [13/3/23 10:43 PM]
/setprompt@WEVChatGPTBot sexy asian

WEV-ChatGPT, [13/3/23 10:43 PM]
😶‍🌫️ Specify arguments for this command. Check /help

WEV-ChatGPT, [13/3/23 10:44 PM]
⏳ Enqueued...

WEV-ChatGPT, [13/3/23 10:44 PM]
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'

WEV-ChatGPT, [13/3/23 10:47 PM]
✅ prompt set

John Pope, [13/3/23 10:47 PM]
/generate@WEVChatGPTBot

WEV-ChatGPT, [13/3/23 10:47 PM]
⏳ Enqueued...

WEV-ChatGPT, [13/3/23 10:47 PM]
❌ Error! Report it to admins: 
🐊 /bot/utils/errorable_command.py:42 
😍 KeyError 
👉 KeyError: 'enabled' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:17 (in generate_command call)
    if not db[DBTables.config]['enabled']:
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
🤯 sqlitedict.py:305 (in __getitem__ call)
    raise KeyError(key)
KeyError: 'enabled'

**Comment by BarsTiger** [comment]
Try using default python 3.10. Install it alongside with your and do not add to PATH variable. Call it from executable, such as `C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\python.exe -m venv venv`. Run bot from this environment

**Comment by BarsTiger** [comment]
Also, run `/start` command. It should resolve some of your issues, like I specified in README.

**Comment by johndpope** [comment]
yep... thx

**Comment by johndpope** [comment]
using miniconda - it's nice.

**Comment by BarsTiger** [comment]
> yep... thx

Thanks also, I will make changes in README to make `/start` command more noticeable
