### ISSUE TITLE
Img2img with controlnet 

### ISSUE THREAD

**Issue by analball** [BarsTiger/TeleDiffusionBot#4]
I tried your bor and it is very cool! 
and also got that kind of error on every image generated
Not sure why
❌ Error! Report it to admins: 
🐊 \bot\utils\errorable_command.py:42 
😍 AttributeError 
👉 AttributeError: 'NoneType' object has no attribute 'groups' 

⬇️ Trace: 
🤯 errorable_command.py:22 (in wrapper call)
    _ = await func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
🤯 txt2img.py:46 (in generate_command call)
    model=re.search(r", Model: ([^,]+),", image[1]['infotexts'][0]).groups()[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by BarsTiger** [comment]
Try checking are all WebUI args right and running `/start` command again. This error means that StableDiffusion WebUI returns wrong answer after generating picture. Also, make `git pull` for WebUI to ensure using latest version. I'll try to reproduce the issue

**Comment by analball** [comment]
![image](https://user-images.githubusercontent.com/16289552/225164914-8423cab7-6b85-42e8-b799-c89bfe8b7692.png)
Fixed by applying gen model name in settings

**Comment by BarsTiger** [comment]
Thanks, I'll add it to README later!
