### ISSUE TITLE
Img2img 

### ISSUE THREAD

**Issue by analball** [BarsTiger/TeleDiffusionBot#5]
It will bit cool to have some guide how to add webui apis to bot 

I think to use telegram draw function to make img2img. with denoise controler (may be even masks for inpainting)
but your structure a little bit complicated to understand for low skilled programmer like me) 
img2img with inpaint mask but with out denoising control here https://github.com/jossalgon/StableDiffusionTelegram 
may be implament it in bot. Big thanks <3

**Comment by BarsTiger** [comment]
Updating not planned at the current time. Feature may be added later. Press `watch` to stay updated, if you want to
