### ISSUE TITLE
гамно

### ISSUE THREAD

**Issue by Cactus-0** [BarsTiger/TeleDiffusionBot#6]
говнище

**Comment by BarsTiger** [comment]
🦛🐊😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
